In [5]:
import matplotlib.pyplot as plt
import numpy as np

A = np.array([
              [31, 0, -16, 0, 0],
              [0, 15 , 0, -6, 0],
              [-16, 0, 39, -3, -20],
              [0, -6, -3, 18, -5],
              [0, 0, -20, -5, 38]
              ])

b = np.array([
              [60],
              [130],
              [-150],
              [0],
              [-160],
              ])


***Q2***

In [2]:
def  triangularInferior(A, b):
  return np.linalg.inv(A) @ b

def triangularSuperior(A, b):
  pass

In [57]:
t = triangularInferior(A, b)
print(t)

[[ -3.60430108]
 [  7.06666667]
 [-10.73333333]
 [ -4.        ]
 [ -8.        ]]


***Q3***


In [1]:
 def decomposicaoLU(A):
  U = A

  dim = list(np.shape(U))
  #print(dim)

  lista_fatores = []

  #print(f'\n0:\n {A}')

  for c in range(0, dim[0]-1):

    for l in range(c+1, dim[0]):
      pivo = U[c][c]
      fator = U[l][c]/pivo
      lista_fatores.append(fator)
      U[l][:] = U[l][:] - fator*U[c][:]

    #print(f'{c+1}:\n {U}\n')

  #print(f'Fatores: {lista_fatores}')

  #print(f'Matriz U:\n{U}',"\n")

  L = np.identity(dim[0])
  
  aux = 0
  for i in range(1, dim[0]):
    for j in range(0, i):
      L[i][j] = lista_fatores[aux]
      aux+=1

  #print(L)

  return L, U

In [53]:
L, U = decomposicaoLU(A)

print("Matriz L:\n",L,"\n\n","Matriz U:\n",U)

Matriz L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.        ]
 [-0.51612903  0.          1.          0.          0.        ]
 [ 0.          0.         -0.4         1.          0.        ]
 [ 0.         -0.1        -0.66666667 -0.5         1.        ]] 

 Matriz U:
 [[ 31   0 -16   0   0]
 [  0  15   0  -6   0]
 [  0   0  30  -3 -20]
 [  0   0   0  14  -7]
 [  0   0   0   0  20]]


***Q4***


In [11]:
def sistemaLinear(A,b):

  L, U = decomposicaoLU(A)

  dim = np.shape(L)

  y = np.zeros((dim[0],1))

  y[0] = b[0]/L[0][0]

  y[1] = (b[1] - (y[0]*L[1][0]))/L[1][1]

  y[2] = (b[2] - (y[0]*L[2][0] - y[1]*L[2][1]))/L[2][2]

  y[3] = (b[3]- (y[0]*L[3][0] - y[1]*L[3][1] - y[2]*L[3][2]))/L[3][3]

  y[4] = (b[4] -(y[0]*L[4][0] - y[1]*L[4][1] - y[2]*L[4][2] - y[3]*L[4][4]))/L[4][4]

  #print(y,"\n")

  x = np.linalg.inv(U) @ y

  print(x,"\n")

  



In [86]:
y = Lyb(L,b)
#print(y,"\n")

x = np.linalg.inv(U) @ y

print(x,"\n")


[[-0.78820078]
 [ 9.56671275]
 [-5.27713902]
 [ 2.25011521]
 [-2.3016129 ]] 



***TESTE***

In [12]:

A = np.array([
              [31,-16,0,0,0],
              [-16,39,0,-3,-20],
              [0,0,15,-6,0],
              [0,-3,-6,18,-5],
              [0,-20,0,-5,38]
              ])

b = np.array([
              [60],
              [-150],
              [130],
              [0],
              [-160],
              ])

L, U = decomposicaoLU(A)

print("Matriz L:\n",L,"\n\n","Matriz U:\n",U,"\n")


sistemaLinear(A,b)

Matriz L:
 [[ 1.          0.          0.          0.          0.        ]
 [-0.51612903  1.          0.          0.          0.        ]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.          0.         -0.1         1.          0.        ]
 [-0.66666667 -0.4         0.         -0.5         1.        ]] 

 Matriz U:
 [[ 31 -16   0   0   0]
 [  0  30   0  -3 -20]
 [  0   0  15  -6   0]
 [  0   0   0  14  -7]
 [  0   0   0   0  20]] 

[[ -3.60430108]
 [-10.73333333]
 [  7.06666667]
 [ -4.        ]
 [ -8.        ]] 

